modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "Apache License 2.0"

[[mods]]
modId = "redderstone"
version = "${version}"
displayName = "Redderstone"
authors = "SSBlur"
description = '''
Like Redstone, but more
'''
#logoFile = ""

[[dependencies.examplemod]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"